"""Added files table

Revision ID: 3b9bdf7bfa44
Revises: ee0fd32abced
Create Date: 2024-05-14 13:29:32.230282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b9bdf7bfa44'
down_revision = 'ee0fd32abced'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jobseeker_id', sa.Integer(), nullable=True),
    sa.Column('employer_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('file_name', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['employer_id'], ['employers.id'], name=op.f('fk_files_employer_id_employers')),
    sa.ForeignKeyConstraint(['jobseeker_id'], ['jobseekers.id'], name=op.f('fk_files_jobseeker_id_jobseekers')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    # ### end Alembic commands ###
