"""Removed excess models

Revision ID: 66ce22f5d8a6
Revises: f3088c1df86a
Create Date: 2024-05-09 21:17:21.222390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66ce22f5d8a6'
down_revision = 'f3088c1df86a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('testimonials')
    op.drop_table('payments')
    op.drop_table('files')
    op.drop_table('offers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('employer_id', sa.INTEGER(), nullable=False),
    sa.Column('job_seeker_id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('accepted', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['employer_id'], ['employers.id'], name='fk_offers_employer_id_employers'),
    sa.ForeignKeyConstraint(['job_seeker_id'], ['jobseekers.id'], name='fk_offers_job_seeker_id_jobseekers'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('files',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('jobseeker_id', sa.INTEGER(), nullable=True),
    sa.Column('file_path', sa.VARCHAR(length=255), nullable=True),
    sa.Column('file_type', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['jobseeker_id'], ['jobseekers.id'], name='fk_files_jobseeker_id_jobseekers'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.Column('payment_date', sa.DATE(), nullable=False),
    sa.Column('payment_status', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_payments_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('testimonials',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('rating', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_testimonials_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
